import requests
import urllib3
from get_census_data import CensusData
from state_fips_codes import STATE_FIPS

def get_nws(state_abbrev, county_fips):
    # Suppress the severe warnings generated by unverified HTTPS requests
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

    url = f"https://api.weather.gov/alerts?zone={state_abbrev}C{county_fips}&limit=500"

    # Fetch the data and parse it into a dictionary
    geojson_data = requests.get(url).json()

    # Count of Warnings and Watches returned
    warnings = 0
    watches = 0

    # Access specific elements
    for feature in geojson_data['features']:
        desc = feature['properties']['description']
        if 'flood warning' in desc.lower() and 'cancelled' not in desc.lower():
            warnings += 1
        if 'flood watch' in desc.lower() and 'cancelled' not in desc.lower():
            watches += 1

    return (warnings, watches)

def get_fips_information(x_coord, y_coord):
    """
    Get the FIPs information for the coordinate
    :param x_coord: The longitude value in decimal degrees.
    :param y_coord: The latitude value in decimal degrees.
    :return: A dictionary containing the county information
    """
    # Get the Census County information
    census_data = CensusData()
    county_dict = census_data.get_county_state_fips(x_coord=x_coord, y_coord=y_coord)

    # TODO: Verify the Zip Code is no longer needed if only NWS and not Accuweather.
    # zip_code_dict = census_data.get_zip_code(x_coord=x_coord, y_coord=y_coord)

    # Merge the two dictionary together
    # county_dict = county_dict | zip_code_dict

    if STATE_FIPS.get(county_dict["state_fips"], None):
        # Append the State Name, abbreviation and FIPs code to the dictionary
        county_dict["State"] = STATE_FIPS[county_dict["state_fips"]][0]
        county_dict["State_Abbrev"] = STATE_FIPS[county_dict["state_fips"]][1]
        county_dict["FIPS6"] = "0" + county_dict["state_fips"] + \
                               county_dict["county_fips"]

    return county_dict

def random_test(iterations=200, extent='world'):
    """Perform a test on random X/Y coordinates."""
    import random
    from datetime import datetime
    random.seed(str(datetime.now()))

    for i in range(iterations):
        x_coord = 0
        y_coord = 0

        # US Based
        if extent.lower() == 'us':
            x_coord = random.uniform(-101, -85)
            y_coord = random.uniform(33, 40)

        # # Entire World
        if extent.lower() == 'world':
            x_coord = random.uniform(-180, 180)
            y_coord = random.uniform(-85, 85)

        main(x_coord, y_coord)

def main(x_coord, y_coord):
    county_info_dict = get_fips_information(x_coord=x_coord, y_coord=y_coord)

    if county_info_dict.get("State_Abbrev", False) and \
       county_info_dict.get("county_fips", False):
        warnings, watches =get_nws(state_abbrev=county_info_dict["State_Abbrev"],
                county_fips=county_info_dict["county_fips"])
        print(warnings, watches)
    else:
        print(f"x={x_coord}, y={y_coord} is invalid or not within the US.")


if __name__ == "__main__":
   x, y = (-77.811651, 39.506993)
   main(x_coord=x, y_coord=y)
