STATE_FIPS = {
    "01": ["Alabama", "AL"],
    "02": ["Alaska", "AK"],
    "60": ["American Samoa", "AS"],
    "04": ["Arizona", "AZ"],
    "05": ["Arkansas", "AR"],
    "81": ["Baker Island", ""],
    "06": ["California", "CA"],
    "08": ["Colorado", "CO"],
    "09": ["Connecticut", "CT"],
    "10": ["Delaware", "DE"],
    "11": ["District of Columbia", "DC"],
    "12": ["Florida", "FL"],
    "64": ["Federated States of Micronesia", "FM"],
    "13": ["Georgia", "GA"],
    "66": ["Guam", "GU"],
    "15": ["Hawaii", "HI"],
    "84": ["Howland Island", ""],
    "16": ["Idaho", "ID"],
    "17": ["Illinois", "IL"],
    "18": ["Indiana", "IN"],
    "19": ["Iowa", "IA"],
    "86": ["Jarvis Island", ""],
    "67": ["Johnston Atoll", ""],
    "20": ["Kansas", "KS"],
    "21": ["Kentucky", "KY"],
    "89": ["Kingman Reef", ""],
    "22": ["Louisiana", "LA"],
    "23": ["Maine", "ME"],
    "68": ["Marshall Islands", "MH"],
    "24": ["Maryland", "MD"],
    "25": ["Massachusetts", "MA"],
    "26": ["Michigan", "MI"],
    "71": ["Midway Islands", ""],
    "27": ["Minnesota", "MN"],
    "28": ["Mississippi", "MS"],
    "29": ["Missouri", "MO"],
    "30": ["Montana", "MT"],
    "76": ["Navassa Island", ""],
    "31": ["Nebraska", "NE"],
    "32": ["Nevada", "NV"],
    "33": ["New Hampshire", "NH"],
    "34": ["New Jersey", "NJ"],
    "35": ["New Mexico", "NM"],
    "36": ["New York", "NY"],
    "37": ["North Carolina", "NC"],
    "38": ["North Dakota", "ND"],
    "69": ["Northern Mariana Islands", "MP"],
    "39": ["Ohio", "OH"],
    "40": ["Oklahoma", "OK"],
    "41": ["Oregon", "OR"],
    "70": ["Palau", "PW"],
    "95": ["Palmyra Atoll", ""],
    "42": ["Pennsylvania", "PA"],
    "72": ["Puerto Rico", "PR"],
    "44": ["Rhode Island", "RI"],
    "45": ["South Carolina", "SC"],
    "46": ["South Dakota", "SD"],
    "47": ["Tennessee", "TN"],
    "48": ["Texas", "TX"],
    "74": ["U.S. Minor Outlying Islands", "UM"],
    "49": ["Utah", "UT"],
    "50": ["Vermont", "VT"],
    "51": ["Virginia", "VA"],
    "78": ["Virgin Islands of the U.S.", "VI"],
    "79": ["Wake Island", ""],
    "53": ["Washington", "WA"],
    "54": ["West Virginia", "WV"],
    "55": ["Wisconsin", "WI"],
    "56": ["Wyoming", "WY"]
}
